#!/bin/bash
echo "🌐 VERCEL DEPLOYMENT HELPER"
echo "=========================="
echo ""
echo "1. Install Vercel CLI (if not already installed):"
echo "   npm i -g vercel"
echo ""
echo "2. Login to Vercel:"
echo "   vercel login"
echo ""
echo "3. Deploy with fixed configuration:"
echo "   cp vercel-fix.json vercel.json"
echo "   vercel --prod"
echo ""
echo "4. Test deployment:"
echo "   curl https://[your-vercel-url]/healthz"
echo ""
echo "Weekend fixes applied for Vercel issues!"
